use anyhow::{Context, Result};
use serde::Deserialize;
use std::path::{Path, PathBuf};

pub fn generate_sample_yaml() -> String {
    r#"# Updatehauler Configuration File
# Default location: ~/.config/updatehauler/config.yaml
# Generated by: updatehauler init

# Enable or disable debug output
debug: false

# Enable or disable datetime stamps in output
datetime: true

# Enable or disable header output
show_header: true

# Enable or disable color output
color: true

# Enable or disable logging to file
use_log: false

# Dry-run mode - show what would be done without making changes
dry_run: false

# Send desktop notification when updates complete
# notify: true

# Maximum lines for logfile before rotation
max_log_lines: 10000

# Logfile path (default: ~/.local/updates.log)
# logfile: ~/.local/updates.log

# Installation directory (default: ~/.local/bin)
# installdir: ~/.local/bin

# Completion files directory (default: ~/.local/share)
# completionsdir: ~/.local/share

# Custom save file locations
# brew_save_file: ~/.config/brew/Darwin-Brewfile
# cargo_save_file: ~/.config/cargo/Darwin-arm64-cargo-backup.json

# Schedule configuration for automated updates
schedule:
  # Minute (0-59, default: 0)
  minute: "0"
  # Hour (0-23, default: 2)
  hour: "2"
  # Day of month (1-31, default: *)
  day_of_month: "*"
  # Month (1-12, default: *)
  month: "*"
  # Day of week (0-7, default: *)
  # 0 and 7 are Sunday
  day_of_week: "*"

# Plugin configuration
plugins:
  # Enable or disable Homebrew plugin
  brew: true
  # Enable or disable Cargo plugin
  cargo: true
  # Enable or disable Neovim plugin
  nvim: false
  # Enable or disable npm plugin
  npm: true
  # Enable or disable OS update plugin
  os: true
  # Enable or disable pip plugin
  pip: true
  # Enable or disable uv plugin
  uv: true
  # Enable or disable rustup plugin
  rustup: true
  # Enable or disable Flatpak plugin
  flatpak: false
  # Enable or disable Snap plugin
  snap: false
  # Enable or disable VSCode extensions plugin
  vscode: true
  # Enable or disable Docker cleanup plugin
  docker: false
  # Enable or disable Ruby gem plugin
  gem: true
  # Enable or disable Deno plugin
  deno: true
  # Enable or disable Yarn plugin
  yarn: false
  # Enable or disable Go module plugin
  go: false"#
        .to_string()
}

pub fn validate_schedule_value(value: &str, field: &str) -> Result<()> {
    if value.is_empty() {
        anyhow::bail!("schedule {} must not be empty", field);
    }
    if !value
        .chars()
        .all(|c| c.is_ascii_digit() || "*,-/".contains(c) || c.is_ascii_alphabetic())
    {
        anyhow::bail!(
            "schedule {} contains invalid characters (only digits, letters, *, -, ,, / allowed): {}",
            field,
            value
        );
    }
    Ok(())
}

pub fn has_path_traversal(path: &Path) -> bool {
    path.components()
        .any(|c| c == std::path::Component::ParentDir)
}

#[derive(Clone, Debug, Deserialize)]
pub struct ConfigFile {
    pub debug: Option<bool>,
    pub datetime: Option<bool>,
    pub show_header: Option<bool>,
    pub color: Option<bool>,
    pub use_log: Option<bool>,
    pub dry_run: Option<bool>,
    pub notify: Option<bool>,
    pub max_log_lines: Option<usize>,
    pub logfile: Option<String>,
    pub installdir: Option<String>,
    pub brew_save_file: Option<String>,
    pub cargo_save_file: Option<String>,
    pub completionsdir: Option<String>,
    pub schedule: Option<ScheduleConfig>,
    pub plugins: Option<PluginConfig>,
}

#[derive(Clone, Debug, Deserialize)]
pub struct ScheduleConfig {
    pub minute: Option<String>,
    pub hour: Option<String>,
    pub day_of_month: Option<String>,
    pub month: Option<String>,
    pub day_of_week: Option<String>,
}

#[derive(Clone, Debug, Deserialize)]
pub struct PluginConfig {
    pub brew: Option<bool>,
    pub cargo: Option<bool>,
    pub nvim: Option<bool>,
    pub os: Option<bool>,
    pub npm: Option<bool>,
    pub pip: Option<bool>,
    pub uv: Option<bool>,
    pub rustup: Option<bool>,
    pub flatpak: Option<bool>,
    pub snap: Option<bool>,
    pub vscode: Option<bool>,
    pub docker: Option<bool>,
    pub gem: Option<bool>,
    pub deno: Option<bool>,
    pub yarn: Option<bool>,
    pub go: Option<bool>,
}

#[derive(Clone)]
pub struct Config {
    pub app_install_dir: PathBuf,
    pub app_name: String,
    pub brew_save_dir: PathBuf,
    pub cargo_save_dir: PathBuf,
    pub completions_dir: PathBuf,
    pub max_log_lines: usize,
    pub sched_minute: String,
    pub sched_hour: String,
    pub sched_day_of_month: String,
    pub sched_month: String,
    pub sched_day_of_week: String,
    pub debug: bool,
    pub datetime: bool,
    pub show_header: bool,
    pub notify: bool,
    pub color: bool,
    pub use_log: bool,
    pub dry_run: bool,
    pub log: PathBuf,
    pub brew_file: PathBuf,
    pub cargo_file: PathBuf,
    pub npm_file: PathBuf,
    pub pip_file: PathBuf,
    pub uv_file: PathBuf,
    pub yarn_file: PathBuf,
    pub go_file: PathBuf,
    pub gem_file: PathBuf,
    pub plugins_enabled: PluginConfig,
    pub cmd_args: Vec<String>,
    pub only_plugin: Option<String>,
}

impl Config {
    pub fn new(home: &str) -> Self {
        let home_path = PathBuf::from(home);

        Self {
            app_install_dir: home_path.join(".local/bin"),
            app_name: "updatehauler".to_string(),
            brew_save_dir: home_path.join(".config/brew"),
            cargo_save_dir: home_path.join(".config/cargo"),
            completions_dir: home_path.join(".local/share"),
            max_log_lines: 10000,
            sched_minute: "0".to_string(),
            sched_hour: "2".to_string(),
            sched_day_of_month: "*".to_string(),
            sched_month: "*".to_string(),
            sched_day_of_week: "*".to_string(),
            debug: false,
            datetime: true,
            notify: false,
            show_header: true,
            color: true,
            use_log: false,
            dry_run: false,
            log: home_path.join(".local/updates.log"),
            brew_file: PathBuf::new(),
            cargo_file: PathBuf::new(),
            npm_file: PathBuf::new(),
            pip_file: PathBuf::new(),
            uv_file: PathBuf::new(),
            yarn_file: PathBuf::new(),
            go_file: PathBuf::new(),
            gem_file: PathBuf::new(),
            plugins_enabled: PluginConfig {
                brew: Some(true),
                cargo: Some(true),
                nvim: Some(false),
                os: Some(true),
                npm: Some(true),
                pip: Some(true),
                uv: Some(true),
                rustup: Some(true),
                flatpak: Some(false),
                snap: Some(false),
                vscode: Some(true),
                docker: Some(false),
                gem: Some(true),
                deno: Some(true),
                yarn: Some(false),
                go: Some(false),
            },
            cmd_args: Vec::new(),
            only_plugin: None,
        }
    }

    pub fn load_from_yaml(home: &str, config_path: Option<&PathBuf>) -> Result<Self> {
        let mut config = Self::new(home);

        let default_config_path = PathBuf::from(home).join(".config/updatehauler/config.yaml");
        let config_file = config_path.unwrap_or(&default_config_path);

        if !config_file.exists() {
            return Ok(config);
        }

        let config_str = std::fs::read_to_string(config_file)
            .context(format!("Failed to read config file: {:?}", config_file))?;

        let config_file_yaml: ConfigFile =
            serde_saphyr::from_str(&config_str).context("Failed to parse YAML configuration")?;

        if let Some(debug) = config_file_yaml.debug {
            config.debug = debug;
        }
        if let Some(datetime) = config_file_yaml.datetime {
            config.datetime = datetime;
        }
        if let Some(show_header) = config_file_yaml.show_header {
            config.show_header = show_header;
        }
        if let Some(color) = config_file_yaml.color {
            config.color = color;
        }
        if let Some(use_log) = config_file_yaml.use_log {
            config.use_log = use_log;
        }
        if let Some(dry_run) = config_file_yaml.dry_run {
            config.dry_run = dry_run;
        }
        if let Some(notify) = config_file_yaml.notify {
            config.notify = notify;
        }
        if let Some(max_log_lines) = config_file_yaml.max_log_lines {
            config.max_log_lines = max_log_lines;
        }
        if let Some(logfile) = config_file_yaml.logfile {
            let p = PathBuf::from(&logfile);
            if has_path_traversal(&p) {
                anyhow::bail!("logfile path contains '..' traversal: {}", logfile);
            }
            config.log = p;
        }
        if let Some(installdir) = config_file_yaml.installdir {
            let p = PathBuf::from(&installdir);
            if has_path_traversal(&p) {
                anyhow::bail!("installdir path contains '..' traversal: {}", installdir);
            }
            config.app_install_dir = p;
        }
        if let Some(completionsdir) = config_file_yaml.completionsdir {
            let p = PathBuf::from(&completionsdir);
            if has_path_traversal(&p) {
                anyhow::bail!(
                    "completionsdir path contains '..' traversal: {}",
                    completionsdir
                );
            }
            config.completions_dir = p;
        }
        if let Some(brew_save_file) = config_file_yaml.brew_save_file {
            let p = PathBuf::from(&brew_save_file);
            if has_path_traversal(&p) {
                anyhow::bail!(
                    "brew_save_file path contains '..' traversal: {}",
                    brew_save_file
                );
            }
            config.brew_file = p;
        }
        if let Some(cargo_save_file) = config_file_yaml.cargo_save_file {
            let p = PathBuf::from(&cargo_save_file);
            if has_path_traversal(&p) {
                anyhow::bail!(
                    "cargo_save_file path contains '..' traversal: {}",
                    cargo_save_file
                );
            }
            config.cargo_file = p;
        }
        if let Some(schedule) = config_file_yaml.schedule {
            if let Some(minute) = schedule.minute {
                validate_schedule_value(&minute, "minute")?;
                config.sched_minute = minute;
            }
            if let Some(hour) = schedule.hour {
                validate_schedule_value(&hour, "hour")?;
                config.sched_hour = hour;
            }
            if let Some(day_of_month) = schedule.day_of_month {
                validate_schedule_value(&day_of_month, "day_of_month")?;
                config.sched_day_of_month = day_of_month;
            }
            if let Some(month) = schedule.month {
                validate_schedule_value(&month, "month")?;
                config.sched_month = month;
            }
            if let Some(day_of_week) = schedule.day_of_week {
                validate_schedule_value(&day_of_week, "day_of_week")?;
                config.sched_day_of_week = day_of_week;
            }
        }
        if let Some(plugins) = config_file_yaml.plugins {
            config.plugins_enabled = plugins;
        }

        Ok(config)
    }

    pub fn apply_plugin_enabled(&mut self, name: &str, enabled: bool) {
        match name {
            "brew" => self.plugins_enabled.brew = Some(enabled),
            "cargo" => self.plugins_enabled.cargo = Some(enabled),
            "nvim" => self.plugins_enabled.nvim = Some(enabled),
            "npm" => self.plugins_enabled.npm = Some(enabled),
            "os" => self.plugins_enabled.os = Some(enabled),
            "pip" => self.plugins_enabled.pip = Some(enabled),
            "uv" => self.plugins_enabled.uv = Some(enabled),
            "rustup" => self.plugins_enabled.rustup = Some(enabled),
            "flatpak" => self.plugins_enabled.flatpak = Some(enabled),
            "snap" => self.plugins_enabled.snap = Some(enabled),
            "vscode" => self.plugins_enabled.vscode = Some(enabled),
            "docker" => self.plugins_enabled.docker = Some(enabled),
            "gem" => self.plugins_enabled.gem = Some(enabled),
            "deno" => self.plugins_enabled.deno = Some(enabled),
            "yarn" => self.plugins_enabled.yarn = Some(enabled),
            "go" => self.plugins_enabled.go = Some(enabled),
            _ => {}
        }
    }

    pub fn crontab_timing(&self) -> String {
        format!(
            "{} {} {} {} {}",
            self.sched_minute,
            self.sched_hour,
            self.sched_day_of_month,
            self.sched_month,
            self.sched_day_of_week
        )
    }

    pub fn crontab_entry(&self, app_path: &std::path::Path) -> String {
        let path_env = self.get_scheduler_path();
        format!(
            "{} PATH={} {} --logfile-only 2>&1",
            self.crontab_timing(),
            path_env,
            app_path.display()
        )
    }

    pub fn get_scheduler_path(&self) -> String {
        let mut path_parts = vec![
            "/usr/local/bin".to_string(),
            "/usr/local/sbin".to_string(),
            "/opt/homebrew/bin".to_string(),
            "/opt/homebrew/sbin".to_string(),
            "/usr/bin".to_string(),
            "/usr/sbin".to_string(),
            "/bin".to_string(),
            "/sbin".to_string(),
        ];

        if let Ok(home) = std::env::var("HOME") {
            path_parts.push(format!("{}/.cargo/bin", home));
        }

        if let Ok(current_path) = std::env::var("PATH") {
            for part in current_path.split(':') {
                if !path_parts.contains(&part.to_string()) {
                    path_parts.push(part.to_string());
                }
            }
        }

        path_parts.join(":")
    }
}
