use anyhow::{Context, Result};
use colored::Colorize;
use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

pub fn generate_sample_yaml() -> String {
    r#"# Updatehauler Configuration File
# Default location: ~/.config/updatehauler/config.yaml
# Generated by: updatehauler init

# Enable or disable debug output
debug: false

# Enable or disable datetime stamps in output
datetime: true

# Enable or disable header output
show_header: true

# Enable or disable color output
color: true

# Enable or disable logging to file
use_log: false

# Dry-run mode - show what would be done without making changes
dry_run: false

# Skip sudo elevation - run commands as current user
# no_sudo: false

# Use sudo for brew upgrade commands (fixes "Operation not permitted" on cask postinstall scripts)
# brew_sudo: false

# Prompt for confirmation before running arbitrary commands
# confirm_run: false

# Send desktop notification when updates complete
# notify: true

# Maximum lines for logfile before rotation
max_log_lines: 10000

# Logfile path (default: ~/.local/updates.log)
# logfile: ~/.local/updates.log

# Installation directory (default: ~/.local/bin)
# installdir: ~/.local/bin

# Completion files directory (default: ~/.local/share)
# completionsdir: ~/.local/share

# Custom save file locations
# brew_save_file: ~/.config/brew/Darwin-Brewfile
# cargo_save_file: ~/.config/cargo/Darwin-arm64-cargo-backup.json

# Schedule configuration for automated updates
schedule:
  # Minute (0-59, default: 0)
  minute: "0"
  # Hour (0-23, default: 2)
  hour: "2"
  # Day of month (1-31, default: *)
  day_of_month: "*"
  # Month (1-12, default: *)
  month: "*"
  # Day of week (0-7, default: *)
  # 0 and 7 are Sunday
  day_of_week: "*"

# Plugin configuration
plugins:
  # Enable or disable Homebrew plugin
  brew: true
  # Enable or disable Cargo plugin
  cargo: true
  # Enable or disable Neovim plugin
  nvim: false
  # Enable or disable npm plugin
  npm: true
  # Enable or disable OS update plugin
  os: true
  # Enable or disable pip plugin
  pip: true
  # Enable or disable uv plugin
  uv: true
  # Enable or disable rustup plugin
  rustup: true
  # Enable or disable Flatpak plugin
  flatpak: false
  # Enable or disable Snap plugin
  snap: false
  # Enable or disable VSCode extensions plugin
  vscode: true
  # Enable or disable Docker cleanup plugin
  docker: false
  # Enable or disable Ruby gem plugin
  gem: true
  # Enable or disable Deno plugin
  deno: true
  # Enable or disable Yarn plugin
  yarn: false
  # Enable or disable Go module plugin
  go: false"#
        .to_string()
}

pub fn validate_schedule_value(value: &str, field: &str) -> Result<()> {
    if value.is_empty() {
        anyhow::bail!("schedule {} must not be empty", field);
    }
    if !value
        .chars()
        .all(|c| c.is_ascii_digit() || "*,-/".contains(c) || c.is_ascii_alphabetic())
    {
        anyhow::bail!(
            "schedule {} contains invalid characters (only digits, letters, *, -, ,, / allowed): {}",
            field,
            value
        );
    }
    Ok(())
}

pub fn has_path_traversal(path: &Path) -> bool {
    path.components()
        .any(|c| c == std::path::Component::ParentDir)
}

#[derive(Clone, Debug, Deserialize)]
pub struct ConfigFile {
    pub debug: Option<bool>,
    pub datetime: Option<bool>,
    pub show_header: Option<bool>,
    pub color: Option<bool>,
    pub use_log: Option<bool>,
    pub dry_run: Option<bool>,
    pub notify: Option<bool>,
    pub no_sudo: Option<bool>,
    pub brew_sudo: Option<bool>,
    pub confirm_run: Option<bool>,
    pub max_log_lines: Option<usize>,
    pub logfile: Option<String>,
    pub installdir: Option<String>,
    pub brew_save_file: Option<String>,
    pub cargo_save_file: Option<String>,
    pub completionsdir: Option<String>,
    pub schedule: Option<ScheduleConfig>,
    pub plugins: Option<PluginConfig>,
}

#[derive(Clone, Debug, Deserialize)]
pub struct ScheduleConfig {
    pub minute: Option<String>,
    pub hour: Option<String>,
    pub day_of_month: Option<String>,
    pub month: Option<String>,
    pub day_of_week: Option<String>,
}

#[derive(Clone, Debug, Deserialize)]
pub struct PluginConfig {
    pub brew: Option<bool>,
    pub cargo: Option<bool>,
    pub nvim: Option<bool>,
    pub os: Option<bool>,
    pub npm: Option<bool>,
    pub pip: Option<bool>,
    pub uv: Option<bool>,
    pub rustup: Option<bool>,
    pub flatpak: Option<bool>,
    pub snap: Option<bool>,
    pub vscode: Option<bool>,
    pub docker: Option<bool>,
    pub gem: Option<bool>,
    pub deno: Option<bool>,
    pub yarn: Option<bool>,
    pub go: Option<bool>,
}

#[derive(Clone)]
pub struct Config {
    pub app_install_dir: PathBuf,
    pub app_name: String,
    pub brew_save_dir: PathBuf,
    pub cargo_save_dir: PathBuf,
    pub completions_dir: PathBuf,
    pub max_log_lines: usize,
    pub sched_minute: String,
    pub sched_hour: String,
    pub sched_day_of_month: String,
    pub sched_month: String,
    pub sched_day_of_week: String,
    pub debug: bool,
    pub datetime: bool,
    pub show_header: bool,
    pub notify: bool,
    pub color: bool,
    pub use_log: bool,
    pub dry_run: bool,
    pub no_sudo: bool,
    pub brew_sudo: bool,
    pub confirm_run: bool,
    pub log: PathBuf,
    pub brew_file: PathBuf,
    pub cargo_file: PathBuf,
    pub npm_file: PathBuf,
    pub pip_file: PathBuf,
    pub uv_file: PathBuf,
    pub yarn_file: PathBuf,
    pub go_file: PathBuf,
    pub gem_file: PathBuf,
    pub plugins_enabled: PluginConfig,
    pub cmd_args: Vec<String>,
    pub only_plugin: Option<String>,
}

impl Config {
    pub fn new(home: &str) -> Self {
        let home_path = PathBuf::from(home);

        Self {
            app_install_dir: home_path.join(".local/bin"),
            app_name: "updatehauler".to_string(),
            brew_save_dir: home_path.join(".config/brew"),
            cargo_save_dir: home_path.join(".config/cargo"),
            completions_dir: home_path.join(".local/share"),
            max_log_lines: 10000,
            sched_minute: "0".to_string(),
            sched_hour: "2".to_string(),
            sched_day_of_month: "*".to_string(),
            sched_month: "*".to_string(),
            sched_day_of_week: "*".to_string(),
            debug: false,
            datetime: true,
            notify: false,
            show_header: true,
            color: true,
            use_log: false,
            dry_run: false,
            no_sudo: false,
            brew_sudo: false,
            confirm_run: false,
            log: home_path.join(".local/updates.log"),
            brew_file: PathBuf::new(),
            cargo_file: PathBuf::new(),
            npm_file: PathBuf::new(),
            pip_file: PathBuf::new(),
            uv_file: PathBuf::new(),
            yarn_file: PathBuf::new(),
            go_file: PathBuf::new(),
            gem_file: PathBuf::new(),
            plugins_enabled: PluginConfig {
                brew: Some(true),
                cargo: Some(true),
                nvim: Some(false),
                os: Some(true),
                npm: Some(true),
                pip: Some(true),
                uv: Some(true),
                rustup: Some(true),
                flatpak: Some(false),
                snap: Some(false),
                vscode: Some(true),
                docker: Some(false),
                gem: Some(true),
                deno: Some(true),
                yarn: Some(false),
                go: Some(false),
            },
            cmd_args: Vec::new(),
            only_plugin: None,
        }
    }

    pub fn load_from_yaml(home: &str, config_path: Option<&PathBuf>) -> Result<Self> {
        let mut config = Self::new(home);

        let default_config_path = PathBuf::from(home).join(".config/updatehauler/config.yaml");
        let config_file = config_path.unwrap_or(&default_config_path);

        if !config_file.exists() {
            return Ok(config);
        }

        let config_str = std::fs::read_to_string(config_file)
            .context(format!("Failed to read config file: {:?}", config_file))?;

        let config_file_yaml: ConfigFile =
            serde_saphyr::from_str(&config_str).context("Failed to parse YAML configuration")?;

        if let Some(debug) = config_file_yaml.debug {
            config.debug = debug;
        }
        if let Some(datetime) = config_file_yaml.datetime {
            config.datetime = datetime;
        }
        if let Some(show_header) = config_file_yaml.show_header {
            config.show_header = show_header;
        }
        if let Some(color) = config_file_yaml.color {
            config.color = color;
        }
        if let Some(use_log) = config_file_yaml.use_log {
            config.use_log = use_log;
        }
        if let Some(dry_run) = config_file_yaml.dry_run {
            config.dry_run = dry_run;
        }
        if let Some(notify) = config_file_yaml.notify {
            config.notify = notify;
        }
        if let Some(no_sudo) = config_file_yaml.no_sudo {
            config.no_sudo = no_sudo;
        }
        if let Some(brew_sudo) = config_file_yaml.brew_sudo {
            config.brew_sudo = brew_sudo;
        }
        if let Some(confirm_run) = config_file_yaml.confirm_run {
            config.confirm_run = confirm_run;
        }
        if let Some(max_log_lines) = config_file_yaml.max_log_lines {
            config.max_log_lines = max_log_lines;
        }
        if let Some(logfile) = config_file_yaml.logfile {
            let p = PathBuf::from(&logfile);
            if has_path_traversal(&p) {
                anyhow::bail!("logfile path contains '..' traversal: {}", logfile);
            }
            config.log = p;
        }
        if let Some(installdir) = config_file_yaml.installdir {
            let p = PathBuf::from(&installdir);
            if has_path_traversal(&p) {
                anyhow::bail!("installdir path contains '..' traversal: {}", installdir);
            }
            config.app_install_dir = p;
        }
        if let Some(completionsdir) = config_file_yaml.completionsdir {
            let p = PathBuf::from(&completionsdir);
            if has_path_traversal(&p) {
                anyhow::bail!(
                    "completionsdir path contains '..' traversal: {}",
                    completionsdir
                );
            }
            config.completions_dir = p;
        }
        if let Some(brew_save_file) = config_file_yaml.brew_save_file {
            let p = PathBuf::from(&brew_save_file);
            if has_path_traversal(&p) {
                anyhow::bail!(
                    "brew_save_file path contains '..' traversal: {}",
                    brew_save_file
                );
            }
            config.brew_file = p;
        }
        if let Some(cargo_save_file) = config_file_yaml.cargo_save_file {
            let p = PathBuf::from(&cargo_save_file);
            if has_path_traversal(&p) {
                anyhow::bail!(
                    "cargo_save_file path contains '..' traversal: {}",
                    cargo_save_file
                );
            }
            config.cargo_file = p;
        }
        if let Some(schedule) = config_file_yaml.schedule {
            if let Some(minute) = schedule.minute {
                validate_schedule_value(&minute, "minute")?;
                config.sched_minute = minute;
            }
            if let Some(hour) = schedule.hour {
                validate_schedule_value(&hour, "hour")?;
                config.sched_hour = hour;
            }
            if let Some(day_of_month) = schedule.day_of_month {
                validate_schedule_value(&day_of_month, "day_of_month")?;
                config.sched_day_of_month = day_of_month;
            }
            if let Some(month) = schedule.month {
                validate_schedule_value(&month, "month")?;
                config.sched_month = month;
            }
            if let Some(day_of_week) = schedule.day_of_week {
                validate_schedule_value(&day_of_week, "day_of_week")?;
                config.sched_day_of_week = day_of_week;
            }
        }
        if let Some(plugins) = config_file_yaml.plugins {
            config.plugins_enabled = plugins;
        }

        Ok(config)
    }

    pub fn default_config_path() -> Result<PathBuf> {
        let home = std::env::var("HOME").context("HOME environment variable not set")?;
        Ok(PathBuf::from(home).join(".config/updatehauler/config.yaml"))
    }

    pub fn config_init(path: Option<&PathBuf>) -> Result<()> {
        let config_path = match path {
            Some(p) => p.clone(),
            None => Self::default_config_path()?,
        };

        if let Some(parent) = config_path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        let yaml = generate_sample_yaml();
        std::fs::write(&config_path, &yaml)?;

        println!("Generated config file: {}", config_path.display());
        println!("Edit this file to customize updatehauler behavior.");
        Ok(())
    }

    pub fn config_compare(path: Option<&PathBuf>) -> Result<()> {
        let config_path = match path {
            Some(p) => p.clone(),
            None => Self::default_config_path()?,
        };

        let default_yaml = generate_sample_yaml();
        let default_val: serde_yaml::Value =
            serde_yaml::from_str(&default_yaml).context("Failed to parse default YAML")?;

        let local_yaml = if config_path.exists() {
            std::fs::read_to_string(&config_path)
                .context(format!("Failed to read config file: {:?}", config_path))?
        } else {
            println!("{}", "No local config file found.".yellow());
            println!("Run `updatehauler config init` to generate one.");
            return Ok(());
        };

        let local_val: serde_yaml::Value =
            serde_yaml::from_str(&local_yaml).context("Failed to parse local YAML config")?;

        let mut default_flat = BTreeMap::new();
        flatten_yaml_value(&default_val, "", &mut default_flat);

        let mut local_flat = BTreeMap::new();
        flatten_yaml_value(&local_val, "", &mut local_flat);

        let mut diffs: Vec<(String, Option<String>, Option<String>)> = Vec::new();

        for key in default_flat.keys() {
            match local_flat.get(key) {
                None => diffs.push((key.clone(), Some(default_flat[key].clone()), None)),
                Some(local_val) => {
                    if local_val != &default_flat[key] {
                        diffs.push((
                            key.clone(),
                            Some(default_flat[key].clone()),
                            Some(local_val.clone()),
                        ));
                    }
                }
            }
        }

        for key in local_flat.keys() {
            if !default_flat.contains_key(key) {
                diffs.push((key.clone(), None, Some(local_flat[key].clone())));
            }
        }

        if diffs.is_empty() {
            println!(
                "{}",
                "Configs are identical. No differences found."
                    .green()
                    .bold()
            );
            return Ok(());
        }

        println!(
            "{}",
            format!("Found {} difference(s):", diffs.len())
                .yellow()
                .bold()
        );
        println!();

        for (key, default_val, local_val) in &diffs {
            match (default_val, local_val) {
                (Some(d), None) => {
                    println!("  {} {} = {}", "+".green().bold(), key.green(), d.green());
                }
                (None, Some(l)) => {
                    println!("  {} {} = {}", "-".red().bold(), key.red(), l.red());
                }
                (Some(d), Some(l)) => {
                    println!("  {} {}:", "~".yellow().bold(), key.yellow());
                    println!("    {} {}", "-".red(), l.red());
                    println!("    {} {}", "+".green(), d.green());
                }
                _ => {}
            }
        }

        Ok(())
    }

    pub fn config_merge(path: Option<&PathBuf>) -> Result<()> {
        let config_path = match path {
            Some(p) => p.clone(),
            None => Self::default_config_path()?,
        };

        let default_yaml = generate_sample_yaml();
        let default_val: serde_yaml::Value =
            serde_yaml::from_str(&default_yaml).context("Failed to parse default YAML")?;

        if !config_path.exists() {
            println!("{}", "No local config file found.".yellow());
            println!("Creating config from defaults...");
            Self::config_init(Some(&config_path))?;
            return Ok(());
        }

        let local_yaml = std::fs::read_to_string(&config_path)
            .context(format!("Failed to read config file: {:?}", config_path))?;

        let local_val: serde_yaml::Value =
            serde_yaml::from_str(&local_yaml).context("Failed to parse local YAML config")?;

        let mut default_flat = BTreeMap::new();
        flatten_yaml_value(&default_val, "", &mut default_flat);

        let mut local_flat = BTreeMap::new();
        flatten_yaml_value(&local_val, "", &mut local_flat);

        let mut diffs: Vec<(String, Option<String>, Option<String>)> = Vec::new();

        for key in default_flat.keys() {
            match local_flat.get(key) {
                None => diffs.push((key.clone(), Some(default_flat[key].clone()), None)),
                Some(local_val) => {
                    if local_val != &default_flat[key] {
                        diffs.push((
                            key.clone(),
                            Some(default_flat[key].clone()),
                            Some(local_val.clone()),
                        ));
                    }
                }
            }
        }

        for key in local_flat.keys() {
            if !default_flat.contains_key(key) {
                diffs.push((key.clone(), None, Some(local_flat[key].clone())));
            }
        }

        if diffs.is_empty() {
            println!(
                "{}",
                "Configs are identical. Nothing to merge.".green().bold()
            );
            return Ok(());
        }

        println!(
            "{}",
            format!("Found {} difference(s) to merge:", diffs.len())
                .yellow()
                .bold()
        );
        println!();

        let mut accepted = 0;
        let mut skipped = 0;

        for (key, default_val, local_val) in &diffs {
            match (default_val, local_val) {
                (Some(d), None) => {
                    println!(
                        "  {} New field: {} = {}",
                        "+".green().bold(),
                        key.green(),
                        d.green()
                    );
                    print!("  Accept new value? [Y/n] ");
                    use std::io::Write;
                    std::io::stdout().flush()?;
                    let mut input = String::new();
                    std::io::stdin().read_line(&mut input)?;
                    if input.trim().is_empty() || input.trim().eq_ignore_ascii_case("y") {
                        local_flat.insert(key.clone(), d.clone());
                        accepted += 1;
                        println!("    {}", "Accepted.".green());
                    } else {
                        skipped += 1;
                        println!("    {} Skipped.", "Kept local.".red());
                    }
                }
                (None, Some(l)) => {
                    println!(
                        "  {} Removed in new: {} (current: {})",
                        "-".red().bold(),
                        key.red(),
                        l.red()
                    );
                    print!("  Accept removal? [Y/n] ");
                    use std::io::Write;
                    std::io::stdout().flush()?;
                    let mut input = String::new();
                    std::io::stdin().read_line(&mut input)?;
                    if input.trim().is_empty() || input.trim().eq_ignore_ascii_case("y") {
                        local_flat.remove(key);
                        accepted += 1;
                        println!("    {}", "Accepted.".green());
                    } else {
                        skipped += 1;
                        println!("    {} Skipped.", "Kept local.".red());
                    }
                }
                (Some(d), Some(l)) => {
                    println!("  {} Changed: {}:", "~".yellow().bold(), key.yellow());
                    println!("    {} Current: {}", "-".red(), l.red());
                    println!("    {} New:     {}", "+".green(), d.green());
                    print!("  Accept new value? [Y/n] ");
                    use std::io::Write;
                    std::io::stdout().flush()?;
                    let mut input = String::new();
                    std::io::stdin().read_line(&mut input)?;
                    if input.trim().is_empty() || input.trim().eq_ignore_ascii_case("y") {
                        local_flat.insert(key.clone(), d.clone());
                        accepted += 1;
                        println!("    {}", "Accepted.".green());
                    } else {
                        skipped += 1;
                        println!("    {} Skipped.", "Kept local.".red());
                    }
                }
                _ => {}
            }
            println!();
        }

        let mut merged = serde_yaml::Value::Mapping(serde_yaml::Mapping::new());
        build_yaml_from_flat(&local_flat, &mut merged);

        let merged_yaml =
            serde_yaml::to_string(&merged).context("Failed to serialize merged YAML")?;

        std::fs::write(&config_path, &merged_yaml)
            .context(format!("Failed to write config file: {:?}", config_path))?;

        println!(
            "{}",
            format!(
                "Merged config written to: {} ({} accepted, {} skipped)",
                config_path.display(),
                accepted,
                skipped
            )
            .green()
            .bold()
        );

        Ok(())
    }

    pub fn apply_plugin_enabled(&mut self, name: &str, enabled: bool) {
        match name {
            "brew" => self.plugins_enabled.brew = Some(enabled),
            "cargo" => self.plugins_enabled.cargo = Some(enabled),
            "nvim" => self.plugins_enabled.nvim = Some(enabled),
            "npm" => self.plugins_enabled.npm = Some(enabled),
            "os" => self.plugins_enabled.os = Some(enabled),
            "pip" => self.plugins_enabled.pip = Some(enabled),
            "uv" => self.plugins_enabled.uv = Some(enabled),
            "rustup" => self.plugins_enabled.rustup = Some(enabled),
            "flatpak" => self.plugins_enabled.flatpak = Some(enabled),
            "snap" => self.plugins_enabled.snap = Some(enabled),
            "vscode" => self.plugins_enabled.vscode = Some(enabled),
            "docker" => self.plugins_enabled.docker = Some(enabled),
            "gem" => self.plugins_enabled.gem = Some(enabled),
            "deno" => self.plugins_enabled.deno = Some(enabled),
            "yarn" => self.plugins_enabled.yarn = Some(enabled),
            "go" => self.plugins_enabled.go = Some(enabled),
            _ => {}
        }
    }

    pub fn crontab_timing(&self) -> String {
        format!(
            "{} {} {} {} {}",
            self.sched_minute,
            self.sched_hour,
            self.sched_day_of_month,
            self.sched_month,
            self.sched_day_of_week
        )
    }

    pub fn crontab_entry(&self, app_path: &std::path::Path) -> String {
        let path_env = self.get_scheduler_path();
        format!(
            "{} PATH={} {} --logfile-only 2>&1",
            self.crontab_timing(),
            path_env,
            app_path.display()
        )
    }

    pub fn get_scheduler_path(&self) -> String {
        let mut path_parts = vec![
            "/usr/local/bin".to_string(),
            "/usr/local/sbin".to_string(),
            "/opt/homebrew/bin".to_string(),
            "/opt/homebrew/sbin".to_string(),
            "/usr/bin".to_string(),
            "/usr/sbin".to_string(),
            "/bin".to_string(),
            "/sbin".to_string(),
        ];

        if let Ok(home) = std::env::var("HOME") {
            path_parts.push(format!("{}/.cargo/bin", home));
        }

        if let Ok(current_path) = std::env::var("PATH") {
            for part in current_path.split(':') {
                if !path_parts.contains(&part.to_string()) {
                    path_parts.push(part.to_string());
                }
            }
        }

        path_parts.join(":")
    }
}

fn flatten_yaml_value(
    value: &serde_yaml::Value,
    prefix: &str,
    result: &mut BTreeMap<String, String>,
) {
    match value {
        serde_yaml::Value::Mapping(map) => {
            for (k, v) in map {
                if let serde_yaml::Value::String(key) = k {
                    let new_prefix = if prefix.is_empty() {
                        key.clone()
                    } else {
                        format!("{}.{}", prefix, key)
                    };
                    flatten_yaml_value(v, &new_prefix, result);
                }
            }
        }
        serde_yaml::Value::Sequence(seq) => {
            for (i, v) in seq.iter().enumerate() {
                let new_prefix = format!("{}.{}", prefix, i);
                flatten_yaml_value(v, &new_prefix, result);
            }
        }
        other => {
            result.insert(
                prefix.to_string(),
                serde_yaml::to_string(other)
                    .unwrap_or_default()
                    .trim()
                    .to_string(),
            );
        }
    }
}

fn build_yaml_from_flat(flat: &BTreeMap<String, String>, root: &mut serde_yaml::Value) {
    for (key, value) in flat {
        let parts: Vec<&str> = key.split('.').collect();
        let last = parts.len() - 1;

        // Navigate to the parent of the leaf, creating intermediate nodes as needed
        let mut node = &mut *root;
        for i in 0..last {
            let part = parts[i].to_string();
            if let serde_yaml::Value::Mapping(map) = node {
                if !map.contains_key(&serde_yaml::Value::String(part.clone())) {
                    map.insert(
                        serde_yaml::Value::String(part.clone()),
                        serde_yaml::Value::Mapping(serde_yaml::Mapping::new()),
                    );
                }
                node = map.get_mut(&serde_yaml::Value::String(part)).unwrap();
            }
        }

        // Insert the value at the leaf
        if let serde_yaml::Value::Mapping(map) = node {
            let parsed =
                serde_yaml::from_str(value).unwrap_or(serde_yaml::Value::String(value.clone()));
            map.insert(serde_yaml::Value::String(parts[last].to_string()), parsed);
        }
    }
}
